app:
  name: QuickPoll
  version: 1.0.0
  environment: production
  debug: false

database:
  type: postgres
  host: ${DATABASE_HOST}
  port: ${DATABASE_PORT}
  user: ${DATABASE_USER}
  password: ${DATABASE_PASSWORD}
  name: ${DATABASE_NAME}
  max_idle_conns: 10
  max_open_conns: 100
  conn_max_lifetime: 1h

redis:
  host: ${REDIS_HOST}
  port: ${REDIS_PORT}
  password: ${REDIS_PASSWORD}
  db: 0
  pool_size: 10
  min_idle_conns: 5
  max_retries: 3

jwt:
  secret: ${JWT_SECRET}
  expiration: 24h

server:
  port: ${PORT}
  read_timeout: 15s
  write_timeout: 15s
  idle_timeout: 60s
  base_url: ${SERVER_BASE_URL}
  frontend_url: ${FRONTEND_URL}