apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://quickpoll_prometheus:9090
    isDefault: true
    editable: true
    basicAuth: false
    withCredentials: false
    jsonData:
      httpMethod: POST
      keepCookies: []
    secureJsonFields: {}
    version: 1
    readOnly: false